// SITEPACKAGES - Configuration File
// This powers sitepackages.net - the store that sells itself
// Generated by setup wizard

window.siteConfig = {
    "site": {
        "name": "SITEPACKAGES",
        "tagline": "Launch your professional storefront in minutes",
        "logo": "https://image.pollinations.ai/prompt/SITEPACKAGES%20modern%20tech%20logo%20purple%20blue%20gradient%20minimalist%20geometric?width=200&height=200&nologo=true",
        "heroBackground": "img/hero-bg.jpg",
        "socialPreview": "img/social-preview.jpg",
        "showHeroText": true,
        "email": "support@sitepackages.net",
        "socialLinks": [
            { "name": "GitHub", "url": "https://github.com/wetwi" }
        ],
        "copyright": "2025 SITEPACKAGES. All rights reserved."
    },
    "colors": {
        "primary": "#667eea",
        "secondary": "#764ba2",
        "tertiary": "#f093fb",
        "highlight": "#4facfe",
        "alert": "#f5576c",
        "background": "#0a0a1a",
        "text": "#ffffff"
    },
    "background": {
        "image": "",
        "sectionImage": ""
    },
    "fonts": {
        "heading": "'Orbitron', sans-serif",
        "body": "'Exo 2', sans-serif"
    },
    "terminology": {
        "category1": "Template",
        "category2": "Add-on",
        "category3": "Service",
        "productTerm": "Package",
        "productPluralTerm": "Packages",
        "packTerm": "License",
        "cartTerm": "Cart",
        "soldOutLabel": "UNAVAILABLE",
        "comingSoonLabel": "COMING SOON"
    },
    "effects": {
        "backgroundEffect": {
            "enabled": true,
            "type": "stars",
            "intensity": "medium"
        },
        "specialFeature": {
            "enabled": false,
            "type": "none",
            "image": "",
            "behavior": ""
        },
        "backgroundAudio": {
            "enabled": false,
            "file": "",
            "volume": 0.5
        }
    },
    "strainTree": {
        "enabled": false,
        "title": "",
        "description": "",
        "dataPath": ""
    },
    "legal": {
        "enableDisclaimer": false,
        "disclaimerText": ""
    },
    "about": {
        "title": "About SITEPACKAGES",
        "subtitle": "Professional Store Templates Made Easy",
        "image": "https://image.pollinations.ai/prompt/modern%20web%20development%20workspace%20with%20code%20screens%20purple%20blue%20gradient%20lighting%20professional?width=600&height=400&nologo=true",
        "description": "SITEPACKAGES provides complete, ready-to-deploy store templates for creators and businesses. Built with modern web technologies, our templates include stunning visual effects, product management, shopping cart, user accounts, and seamless checkout integration.\n\nNo coding required - just configure through our setup wizard and launch your professional storefront in minutes, not months.",
        "teamMembers": [
            {
                "name": "Rev",
                "title": "Creator & Lead Developer",
                "bio": "Building AI systems and web tools for over a decade. Creator of numerous projects including StrainNavigator and Rev's Genetics.",
                "image": "https://image.pollinations.ai/prompt/cyberpunk%20hacker%20portrait%20purple%20neon%20lighting%20dark%20background?width=200&height=200&nologo=true"
            }
        ],
        "historyItems": [
            {
                "year": "2024",
                "title": "Genesis",
                "description": "Rev's Genetics site template created with full e-commerce capabilities."
            },
            {
                "year": "2025",
                "title": "SITEPACKAGES Launch",
                "description": "Template system released publicly with setup wizard, visual effects, and licensing system."
            }
        ],
        "additionalSections": [
            {
                "title": "Why SITEPACKAGES?",
                "content": "Building a professional e-commerce site from scratch takes weeks or months. With SITEPACKAGES, you get a complete store template with product grids, detail modals, shopping cart, user accounts, and beautiful visual effects - all configurable through our setup wizard."
            },
            {
                "title": "Features Included",
                "content": "Product grid with filtering, detailed product modals with tabs, shopping cart system, checkout flow, age verification, cookie consent, background effects (particles, stars, matrix), floating objects, partner showcases, about pages with team members and timelines, and much more."
            }
        ]
    },
    "products": {
        "defaultStatus": "available",
        "enableRatings": true,
        "showPackOptions": true,
        "defaultPackOptions": [
            {
                "size": "License",
                "regularPrice": 29,
                "salePrice": null
            }
        ],
        "items": {
            "starter": {
                "id": "starter",
                "name": "Starter Package",
                "type": "Template",
                "status": "available",
                "delivery": "digital",
                "digitalContent": "",
                "image": "https://image.pollinations.ai/prompt/minimalist%20website%20template%20mockup%20on%20laptop%20purple%20gradient%20background%20clean%20design?width=400&height=400&nologo=true",
                "additionalImages": [],
                "description": "Perfect for personal projects and small businesses. Get started with our full-featured template at an affordable price.",
                "variety": "Single Site",
                "rating": 4,
                "origin": "SITEPACKAGES",
                "rarity": "Standard",
                "details": "Includes: Full template source code, Setup wizard access, Product grid & modals, Shopping cart, Background effects, Age verification, Cookie consent, Community support via GitHub",
                "notes": "Attribution required - 'Powered by SITEPACKAGES' footer link must remain visible.",
                "packOptions": [
                    { "size": "1 Site License", "regularPrice": 29, "salePrice": 19 }
                ],
                "enableHoverImage": false,
                "hoverImage": "",
                "hidden": false,
                "displayOrder": 1,
                "promotional": {
                    "type": "percentage",
                    "value": "35",
                    "discountPercent": "35",
                    "bogoType": "same",
                    "enabled": true
                }
            },
            "pro": {
                "id": "pro",
                "name": "Pro Package",
                "type": "Template",
                "status": "available",
                "delivery": "digital",
                "digitalContent": "",
                "image": "https://image.pollinations.ai/prompt/professional%20ecommerce%20website%20template%20multiple%20screens%20blue%20purple%20gradient%20premium?width=400&height=400&nologo=true",
                "additionalImages": [],
                "description": "For serious businesses ready to launch. Includes priority support and all the bells and whistles.",
                "variety": "Single Site",
                "rating": 5,
                "origin": "SITEPACKAGES",
                "rarity": "Premium",
                "details": "Everything in Starter PLUS: Priority email support (30 days), All background effects unlocked, Partner showcase section, Extended about page features, Promotion system, Inventory management",
                "notes": "Attribution required - 'Powered by SITEPACKAGES' footer link must remain visible. Commercial use allowed.",
                "packOptions": [
                    { "size": "1 Site License", "regularPrice": 79, "salePrice": 59 }
                ],
                "enableHoverImage": false,
                "hoverImage": "",
                "hidden": false,
                "displayOrder": 2,
                "promotional": {
                    "type": "percentage",
                    "value": "25",
                    "discountPercent": "25",
                    "bogoType": "same",
                    "enabled": true
                }
            },
            "business": {
                "id": "business",
                "name": "Business Package",
                "type": "Template",
                "status": "available",
                "delivery": "digital",
                "digitalContent": "",
                "image": "https://image.pollinations.ai/prompt/enterprise%20web%20application%20dashboard%20multiple%20monitors%20gold%20purple%20gradient%20luxury?width=400&height=400&nologo=true",
                "additionalImages": [],
                "description": "The complete package for agencies and resellers. White-label rights let you brand it as your own.",
                "variety": "White Label",
                "rating": 5,
                "origin": "SITEPACKAGES",
                "rarity": "Exclusive",
                "details": "Everything in Pro PLUS: WHITE-LABEL RIGHTS (remove attribution), 1-hour setup consultation call, Priority support (90 days), Custom theme assistance, License for client resale",
                "notes": "Full white-label rights - remove all SITEPACKAGES branding. Perfect for agencies building sites for clients.",
                "packOptions": [
                    { "size": "1 Site License", "regularPrice": 199, "salePrice": 149 }
                ],
                "enableHoverImage": false,
                "hoverImage": "",
                "hidden": false,
                "displayOrder": 3,
                "promotional": {
                    "type": "percentage",
                    "value": "25",
                    "discountPercent": "25",
                    "bogoType": "same",
                    "enabled": true
                }
            },
            "effects-pack": {
                "id": "effects-pack",
                "name": "Effects Add-on Pack",
                "type": "Add-on",
                "status": "available",
                "delivery": "digital",
                "digitalContent": "",
                "image": "https://image.pollinations.ai/prompt/abstract%20particle%20effects%20stars%20matrix%20code%20purple%20blue%20gradient%20digital?width=400&height=400&nologo=true",
                "additionalImages": [],
                "description": "Additional visual effects to make your site stand out. Includes particles, matrix rain, custom floating objects, and more.",
                "variety": "Enhancement",
                "rating": 4,
                "origin": "SITEPACKAGES",
                "rarity": "Standard",
                "details": "Includes: 5 additional particle styles, Matrix code rain effect, Custom floating object support, Parallax backgrounds, Animated gradients",
                "notes": "Requires Starter or higher. Effects are applied via config.js settings.",
                "packOptions": [
                    { "size": "Add-on", "regularPrice": 19, "salePrice": null }
                ],
                "enableHoverImage": false,
                "hoverImage": "",
                "hidden": false,
                "displayOrder": 4,
                "promotional": {
                    "type": "new",
                    "value": "NEW",
                    "enabled": true
                }
            },
            "setup-service": {
                "id": "setup-service",
                "name": "Setup Service",
                "type": "Service",
                "status": "available",
                "delivery": "digital",
                "digitalContent": "",
                "image": "https://image.pollinations.ai/prompt/professional%20consultation%20video%20call%20screen%20share%20purple%20neon%20lighting?width=400&height=400&nologo=true",
                "additionalImages": [],
                "description": "Let us handle the setup for you. We'll configure your template, add your products, and get you live.",
                "variety": "Service",
                "rating": 5,
                "origin": "SITEPACKAGES",
                "rarity": "Premium",
                "details": "Includes: Full template configuration, Product entry (up to 20 products), Color/branding customization, Deployment assistance, 30-minute walkthrough call",
                "notes": "Requires purchase of any template package. Service delivered within 3 business days.",
                "packOptions": [
                    { "size": "Setup Service", "regularPrice": 99, "salePrice": null }
                ],
                "enableHoverImage": false,
                "hoverImage": "",
                "hidden": false,
                "displayOrder": 5,
                "promotional": {
                    "type": "custom",
                    "value": "BEST SELLER",
                    "enabled": true
                }
            },
            "custom-themes": {
                "id": "custom-themes",
                "name": "Custom Themes",
                "type": "Template",
                "status": "comingSoon",
                "delivery": "digital",
                "digitalContent": "",
                "image": "https://image.pollinations.ai/prompt/futuristic%20website%20themes%20collection%20multiple%20color%20schemes%20purple%20gold%20blue%20preview%20grid%20premium%20design?width=400&height=400&nologo=true",
                "additionalImages": [],
                "description": "Premium theme packs coming soon! Transform your SITEPACKAGES site with professionally designed color schemes, layouts, and visual styles. Each theme includes custom CSS, background effects, and UI variations.",
                "variety": "Theme Pack",
                "rating": 5,
                "origin": "SITEPACKAGES",
                "rarity": "Premium",
                "details": "Coming Soon: Neon Cyberpunk theme, Earth & Nature theme, Luxury Gold theme, Minimalist Clean theme, Retro Arcade theme. Each theme includes color presets, custom effects, and layout variations.",
                "notes": "Join our mailing list to be notified when premium themes launch. Early subscribers get 25% off.",
                "packOptions": [
                    { "size": "Theme Pack", "regularPrice": 29, "salePrice": null }
                ],
                "enableHoverImage": false,
                "hoverImage": "",
                "hidden": false,
                "displayOrder": 6,
                "promotional": {
                    "type": "custom",
                    "value": "COMING SOON",
                    "bogoType": "same",
                    "enabled": true
                }
            },
            "image-pack-starter": {
                "id": "image-pack-starter",
                "name": "Image Pack - Starter",
                "type": "Add-on",
                "status": "comingSoon",
                "delivery": "digital",
                "digitalContent": "",
                "image": "https://image.pollinations.ai/prompt/collection%20of%20website%20textures%20backgrounds%20seamless%20patterns%20dark%20theme%20purple%20blue%20gradient%20grid%20preview?width=400&height=400&nologo=true",
                "additionalImages": [
                    "https://image.pollinations.ai/prompt/seamless%20dark%20grunge%20texture%20concrete%20subtle%20noise%20website%20background?width=400&height=400&nologo=true",
                    "https://image.pollinations.ai/prompt/purple%20blue%20gradient%20background%20smooth%20transition%20dark%20edges%20website%20hero?width=400&height=400&nologo=true",
                    "https://image.pollinations.ai/prompt/geometric%20hexagon%20pattern%20dark%20theme%20subtle%20lines%20tech%20background?width=400&height=400&nologo=true"
                ],
                "description": "Essential background textures and patterns for your SITEPACKAGES site. Perfect for hero sections, cards, and overlays.",
                "variety": "Digital Assets",
                "rating": 4,
                "origin": "SITEPACKAGES",
                "rarity": "Standard",
                "details": "Includes 15 high-quality assets: 5 seamless dark textures (grunge, noise, fabric, concrete, paper), 5 gradient backgrounds (purple-blue, sunset, ocean, forest, midnight), 5 abstract patterns (geometric, circuit, hexagon, wave, dots). All images 2048x2048px, PNG format, royalty-free for your sites.",
                "notes": "Drop into your img/ folder and reference in config.js. Works with any SITEPACKAGES template.",
                "packOptions": [
                    { "size": "15 Assets", "regularPrice": 9, "salePrice": 7 }
                ],
                "enableHoverImage": true,
                "hoverImage": "https://image.pollinations.ai/prompt/seamless%20dark%20texture%20pack%20preview%20grunge%20noise%20concrete%20samples%20grid?width=400&height=400&nologo=true",
                "hidden": false,
                "displayOrder": 7,
                "promotional": {
                    "type": "custom",
                    "value": "COMING SOON",
                    "enabled": true
                }
            },
            "image-pack-pro": {
                "id": "image-pack-pro",
                "name": "Image Pack - Pro",
                "type": "Add-on",
                "status": "comingSoon",
                "delivery": "digital",
                "digitalContent": "",
                "image": "https://image.pollinations.ai/prompt/premium%20website%20asset%20collection%20textures%20backgrounds%20overlays%20particles%20dark%20theme%20professional%20grid%20showcase?width=400&height=400&nologo=true",
                "additionalImages": [
                    "https://image.pollinations.ai/prompt/metallic%20brushed%20steel%20texture%20dark%20theme%20industrial%20seamless?width=400&height=400&nologo=true",
                    "https://image.pollinations.ai/prompt/particle%20overlay%20sparkles%20dust%20floating%20transparent%20background%20bokeh?width=400&height=400&nologo=true",
                    "https://image.pollinations.ai/prompt/epic%20hero%20background%20mountain%20sunset%20cinematic%20wide%20landscape%20dark%20moody?width=400&height=400&nologo=true",
                    "https://image.pollinations.ai/prompt/abstract%20wave%20pattern%20flowing%20lines%20dark%20blue%20purple%20gradient?width=400&height=400&nologo=true"
                ],
                "description": "Comprehensive image library with textures, backgrounds, overlays, and UI elements. Everything you need for a polished site.",
                "variety": "Digital Assets",
                "rating": 5,
                "origin": "SITEPACKAGES",
                "rarity": "Premium",
                "details": "Includes 50 high-quality assets: 10 seamless textures (dark, light, grunge, metallic, organic), 15 gradient backgrounds (all color themes), 10 abstract patterns, 5 particle overlays (PNG with transparency), 5 hero backgrounds (landscape 3840x2160), 5 card/section backgrounds. All royalty-free.",
                "notes": "Includes size variations for each asset (full, medium, thumbnail). Perfect for performance optimization.",
                "packOptions": [
                    { "size": "50 Assets", "regularPrice": 24, "salePrice": 19 }
                ],
                "enableHoverImage": true,
                "hoverImage": "https://image.pollinations.ai/prompt/professional%20asset%20pack%20preview%20textures%20gradients%20overlays%20samples%20dark?width=400&height=400&nologo=true",
                "hidden": false,
                "displayOrder": 8,
                "promotional": {
                    "type": "custom",
                    "value": "COMING SOON",
                    "enabled": true
                }
            },
            "image-pack-holiday": {
                "id": "image-pack-holiday",
                "name": "Image Pack - Holiday Bundle",
                "type": "Add-on",
                "status": "comingSoon",
                "delivery": "digital",
                "digitalContent": "",
                "image": "https://image.pollinations.ai/prompt/holiday%20themed%20website%20backgrounds%20christmas%20halloween%20valentines%20easter%20festive%20collection%20dark%20theme%20preview%20grid?width=400&height=400&nologo=true",
                "additionalImages": [
                    "https://image.pollinations.ai/prompt/christmas%20background%20snowflakes%20blue%20winter%20festive%20dark%20elegant?width=400&height=400&nologo=true",
                    "https://image.pollinations.ai/prompt/halloween%20spooky%20background%20orange%20black%20fog%20bats%20moonlight?width=400&height=400&nologo=true",
                    "https://image.pollinations.ai/prompt/valentines%20hearts%20background%20red%20pink%20romantic%20bokeh%20love?width=400&height=400&nologo=true",
                    "https://image.pollinations.ai/prompt/summer%20tropical%20background%20beach%20sunset%20palm%20trees%20warm%20colors?width=400&height=400&nologo=true"
                ],
                "description": "Seasonal backgrounds and textures for every holiday. Keep your site fresh year-round with themed visuals.",
                "variety": "Seasonal Assets",
                "rating": 5,
                "origin": "SITEPACKAGES",
                "rarity": "Premium",
                "details": "Includes 40 seasonal assets across 8 holidays: Christmas (snowflakes, trees, lights), Halloween (spooky, pumpkins, bats), Valentine's (hearts, roses, romance), Easter (pastels, eggs, spring), St. Patrick's (green, clovers, gold), Summer (beach, tropical, sun), Fall (leaves, harvest, warm), New Year's (fireworks, celebration, sparkle). Each holiday pack includes 5 backgrounds.",
                "notes": "Pairs perfectly with our holiday floating effects! Use together for maximum seasonal impact.",
                "packOptions": [
                    { "size": "40 Assets (8 Holidays)", "regularPrice": 29, "salePrice": 22 }
                ],
                "enableHoverImage": true,
                "hoverImage": "https://image.pollinations.ai/prompt/four%20seasons%20holiday%20backgrounds%20grid%20christmas%20halloween%20summer%20spring?width=400&height=400&nologo=true",
                "hidden": false,
                "displayOrder": 9,
                "promotional": {
                    "type": "custom",
                    "value": "COMING SOON",
                    "enabled": true
                }
            },
            "image-pack-ultimate": {
                "id": "image-pack-ultimate",
                "name": "Image Pack - Ultimate Bundle",
                "type": "Add-on",
                "status": "comingSoon",
                "delivery": "digital",
                "digitalContent": "",
                "image": "https://image.pollinations.ai/prompt/ultimate%20website%20asset%20bundle%20textures%20backgrounds%20overlays%20icons%20everything%20dark%20premium%20gold%20accents%20showcase?width=400&height=400&nologo=true",
                "additionalImages": [
                    "https://image.pollinations.ai/prompt/animated%20gif%20background%20subtle%20particles%20flowing%20dark%20elegant?width=400&height=400&nologo=true",
                    "https://image.pollinations.ai/prompt/social%20media%20template%20pack%20instagram%20twitter%20dark%20theme%20preview?width=400&height=400&nologo=true",
                    "https://image.pollinations.ai/prompt/ui%20elements%20sprites%20buttons%20icons%20dark%20theme%20web%20design%20collection?width=400&height=400&nologo=true",
                    "https://image.pollinations.ai/prompt/email%20header%20graphics%20newsletter%20banners%20professional%20dark%20purple?width=400&height=400&nologo=true",
                    "https://image.pollinations.ai/prompt/premium%20particle%20overlays%20collection%20sparkles%20smoke%20light%20rays%20transparent?width=400&height=400&nologo=true"
                ],
                "description": "The complete image library. Every texture, background, overlay, and seasonal asset we offer, plus exclusive bonus content.",
                "variety": "Complete Bundle",
                "rating": 5,
                "origin": "SITEPACKAGES",
                "rarity": "Exclusive",
                "details": "EVERYTHING included: All 50 Pro assets, All 40 Holiday assets, PLUS 30 exclusive bonus items - animated GIF backgrounds, premium particle overlays, UI element sprites, social media templates, and email header graphics. 120+ assets total, regularly updated with new content.",
                "notes": "Best value! Includes lifetime updates - get new assets added to the bundle automatically. One purchase, forever expanding library.",
                "packOptions": [
                    { "size": "120+ Assets + Updates", "regularPrice": 59, "salePrice": 39 }
                ],
                "enableHoverImage": true,
                "hoverImage": "https://image.pollinations.ai/prompt/ultimate%20bundle%20everything%20included%20textures%20overlays%20templates%20gold%20premium?width=400&height=400&nologo=true",
                "hidden": false,
                "displayOrder": 10,
                "promotional": {
                    "type": "bogo",
                    "value": "BOGO",
                    "enabled": true
                }
            }
        }
    },
    "navigation": [
        { "name": "Packages", "url": "#products" },
        { "name": "Features", "url": "features.html" },
        { "name": "Setup Wizard", "url": "setup.html" },
        { "name": "About", "url": "#about" }
    ],
    "friendLinks": [
        { "name": "Rev's Genetics", "url": "https://revsgeneticslab.com/", "image": "img/friends/revs-genetics.jpg", "description": "Premium cannabis genetics" },
        { "name": "Dwarven Forged", "url": "https://www.dwarvenforged.club/", "image": "img/friends/dwarvenforged.jpg", "description": "Built with SITEPACKAGES" }
    ],
    "friendLinksShowcase": {
        "enabled": true,
        "style": "cards",
        "title": "Built With SITEPACKAGES"
    },
    "showFooterFriendLinks": true,
    "advanced": {
        "enableShop": true,
        "enableLocalStorage": true,
        "enableShipping": false,
        "shippingPrice": 10,
        "showFreeShipping": true,
        "checkoutMethod": "email",
        "externalCheckoutUrl": "",
        "orderEmail": "support@sitepackages.net",
        "paymentProcessor": {
            "type": "none",
            "square": {
                "appId": "",
                "locationId": "",
                "environment": "sandbox"
            },
            "stripe": {
                "publishableKey": "",
                "environment": "test"
            },
            "paypal": {
                "clientId": "",
                "environment": "sandbox",
                "currency": "USD"
            }
        },
        "enableAgeCheck": false,
        "ageCheckMinimum": 21,
        "ageRedirectUrl": "https://www.google.com",
        "enableCookieConsent": true,
        "cookiePolicyUrl": "./privacy.html",
        "cookieRedirectOnDecline": false,
        "analyticsId": ""
    }
};
