// SITEPACKAGES - Configuration File
// This powers sitepackages.net - the store that sells itself
// Generated by setup wizard

window.siteConfig = {
    "site": {
        "name": "SITEPACKAGES",
        "tagline": "Launch your professional storefront in minutes",
        "logo": "img/logo.png",
        "heroBackground": "img/hero-bg.jpg",
        "socialPreview": "img/social-preview.jpg",
        "showHeroText": true,
        "email": "support@sitepackages.net",
        "socialLinks": [
            { "name": "GitHub", "url": "https://github.com/wetwi" }
        ],
        "copyright": "2025 SITEPACKAGES. All rights reserved."
    },
    "colors": {
        "primary": "#667eea",
        "secondary": "#764ba2",
        "tertiary": "#f093fb",
        "highlight": "#4facfe",
        "alert": "#f5576c",
        "background": "#0a0a1a",
        "text": "#ffffff"
    },
    "background": {
        "image": "",
        "sectionImage": ""
    },
    "fonts": {
        "heading": "'Orbitron', sans-serif",
        "body": "'Exo 2', sans-serif"
    },
    "terminology": {
        "category1": "Package",
        "category2": "Add-on",
        "category3": "Service",
        "productTerm": "Package",
        "productPluralTerm": "Packages",
        "packTerm": "License",
        "cartTerm": "Cart",
        "soldOutLabel": "UNAVAILABLE",
        "comingSoonLabel": "COMING SOON"
    },
    "effects": {
        "backgroundEffect": {
            "enabled": true,
            "type": "stars",
            "intensity": "medium"
        },
        "specialFeature": {
            "enabled": false,
            "type": "none",
            "image": "",
            "behavior": ""
        },
        "backgroundAudio": {
            "enabled": false,
            "file": "",
            "volume": 0.5
        }
    },
    "strainTree": {
        "enabled": false,
        "title": "",
        "description": "",
        "dataPath": ""
    },
    "legal": {
        "enableDisclaimer": false,
        "disclaimerText": ""
    },
    "about": {
        "title": "About SITEPACKAGES",
        "subtitle": "Professional Store Templates",
        "image": "img/about.jpg",
        "description": "SITEPACKAGES provides complete, ready-to-deploy store templates for creators and businesses. Built with modern web technologies, our templates include visual effects, product management, user authentication, and seamless checkout integration. Launch your professional storefront in minutes, not months.",
        "teamMembers": [],
        "historyItems": [
            {
                "year": "2025",
                "title": "Launch",
                "description": "SITEPACKAGES launches with full-featured store templates including Supabase integration, visual effects, and setup wizard."
            }
        ],
        "additionalSections": [
            {
                "title": "Why SITEPACKAGES?",
                "content": "Building a professional e-commerce site from scratch takes weeks or months. With SITEPACKAGES, you get a complete store template with product grids, detail modals, shopping cart, user accounts, and beautiful visual effects - all configurable through our setup wizard. No coding required."
            }
        ]
    },
    "products": {
        "defaultStatus": "available",
        "enableRatings": false,
        "showPackOptions": true,
        "defaultPackOptions": [
            {
                "size": "License",
                "regularPrice": 29,
                "salePrice": null
            }
        ],
        "items": {}
    },
    "navigation": [
        { "name": "Packages", "url": "#products" },
        { "name": "Features", "url": "features.html" },
        { "name": "Setup", "url": "setup.html" },
        { "name": "About", "url": "#about" }
    ],
    "friendLinks": [
        { "name": "Rev's Genetics", "url": "https://revsgeneticslab.com/", "image": "", "description": "" },
        { "name": "StrainNavigator", "url": "https://www.strainnavigator.com/", "image": "", "description": "" }
    ],
    "friendLinksShowcase": {
        "enabled": false,
        "style": "cards",
        "title": "Friends and Sponsors"
    },
    "showFooterFriendLinks": true,
    "advanced": {
        "enableShop": true,
        "enableLocalStorage": true,
        "checkoutMethod": "email",
        "externalCheckoutUrl": "",
        "analyticsId": "",
        "orderEmail": "support@sitepackages.net",
        "enableAgeCheck": false,
        "ageCheckMinimum": 21,
        "ageRedirectUrl": "https://www.google.com"
    }
};
